check/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView, RedirectView
from django.contrib import admin



urlpatterns = patterns(

    "",
    # url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),
    # url(r"^$", "checkapp.views.homepage", name="home"),
    
    url(r'^$', RedirectView.as_view(url='/account/login/'), name="home"),
    url(r"^check/", include("checkapp.urls")),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^account/", include("account.urls")),
    url(r"^ipad/", include("ipad.urls")),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# print urlpatterns

ipad/urls.py
from django.conf import settings
from django.conf.urls import patterns, url, include
from rest_framework.authtoken import views as token_view
# import views_account
from rest_framework import routers
from ipad import views
from ipad import admin_view


router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'publish', views.PublishViewSet)
router.register(r'publish_v1', views.PublishViewSetV1, base_name="publish_v1")
router.register(r'meeting', views.MeetingViewSet)
router.register(r'meeting_v1', views.MeetingViewSetV1, base_name="meeting_v1")
router.register(r'exhibiting', views.ExhibitingViewSet)
router.register(r'training', views.TrainingViewSet)
router.register(r'training_v1', views.TrainingViewSetV1)
router.register(r'notifacation', views.NotifacationViewSet)
router.register(r'notifacation_v1', views.NotifacationViewSetV1, base_name="notifacation_v1")
router.register(r'help', views.IpadHelpViewSet)
router.register(r'updatetime', views.UpdateTimeViewSet, base_name="updatetime")
router.register(r'meeting_date', views.MeetingAvaiableDate, base_name="meeting_date")
router.register(r'notification_date', views.NotificationAvaiableDate, base_name="notification_date")
router.register(r'publish_date', views.PublishAvaiableDate, base_name="publish_date")

urlpatterns = patterns(
    "ipad.views",
    url(r'^api-token-auth/', token_view.obtain_auth_token),
    url(r'^api/', include(router.urls)),
    # url(r'^api/updatetime/$', views.update_time, name='updatetime'),
    # url(r'^api/getupdatetime/$', views.GetUpdateTime.as_view(), name='getupdatetime'),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # 
    url(r'^api/terms_of_service/$', views.terms_of_service, name='terms_of_service'),

    # admin
    # publish
    url(r'^admin/publish/$', admin_view.publish_list, name="publish_list"),
    url(r'^admin/publish/(?P<pk>\d+)/$', admin_view.publish_update),
    url(r'^admin/publish/(?P<pk>\d+)/delete/$', admin_view.publish_delete),
    url(r'^admin/publish/add/$', admin_view.publish_add),

    # meeting
    url(r'^admin/meeting/$', admin_view.meeting_list, name="meeting_list"),
    url(r'^admin/meeting/(?P<pk>\d+)/$', admin_view.meeting_update),
    url(r'^admin/meeting/(?P<pk>\d+)/delete/$', admin_view.meeting_delete),
    url(r'^admin/meeting/add/$', admin_view.meeting_add),

    # training
    url(r'^admin/training/$', admin_view.training_list, name="training_list"),
    url(r'^admin/training/(?P<pk>\d+)/$', admin_view.training_update),
    url(r'^admin/training/(?P<pk>\d+)/delete/$', admin_view.training_delete),
    url(r'^admin/training/add/$', admin_view.training_add),

    # exhibition
    url(r'^admin/exhibiting/$', admin_view.exhibiting_list, name="exhibiting_list"),
    url(r'^admin/exhibiting/(?P<pk>\d+)/$', admin_view.exhibiting_update),
    url(r'^admin/exhibiting/(?P<pk>\d+)/delete/$', admin_view.exhibiting_delete),
    url(r'^admin/exhibiting/add/$', admin_view.exhibiting_add),

    # noticafacion
    url(r'^admin/notification/$', admin_view.notifacation_list, name='notifacation_list'),
    url(r'^admin/notification/(?P<pk>\d+)/$', admin_view.notifacation_update),
    url(r'^admin/notification/add/$', admin_view.notifacation_add, name='notifacation_add'),
    url(r'^admin/notification/(?P<pk>\d+)/delete/$',  admin_view.notifacation_delete, name='notifacation_delete'),

    # help
    # 
    url(r'^admin/help/$', admin_view.IpadHelpList.as_view(template_name="ipad/ipad_help_list.html"), name='help_list'),
    url(r'admin/help/(?P<pk>\d+)/$', admin_view.IpadHelpUpdate.as_view(template_name="ipad/ipad_help_update.html"), name='help_update'),
    url(r'admin/help/delete/(?P<pk>\d+)/$', admin_view.IpadHelpDelete.as_view(template_name="ipad/ipad_help_delete.html"), name='help_delete'),
    url(r'admin/help/add/$', admin_view.IpadHelpAdd.as_view(template_name="ipad/ipad_help_add.html"), name='help_add'),

    # file to client
    # url(r'^file_to_client/$', views.file_to_client, name='file_to_client'),

    # backend admin
    # url(r'^publish/$', 'publish', name='publish'),
)

ipad/models.py
# -*- coding: utf-8 -*-

from datetime import datetime
from checkapp.models import MyUser
from django.db import models
from django.core.validators import MaxLengthValidator


def get_file_path(instance, filename):
    # import pdb; pdb.set_trace()
    dd = instance.created_time.__str__()
    dd = dd.replace(":", "-")
    file_name = instance.__class__.__name__ + '/' + dd + '/' + filename
    # print 
    return file_name

#####################----Publish----#######################

class Publish(models.Model):
    user = models.ForeignKey(MyUser)
    name = models.CharField(u'名称', max_length=50)
    desc = models.TextField(u'描述', blank=True)
    created_time = models.DateTimeField(u'上传时间', default=datetime.now)
    def __unicode__(self):
        return "Publish--" + self.created_time.__str__()
    class Meta:
        ordering = ['-created_time']

class PublishFile(models.Model):
    publish = models.ForeignKey(Publish, related_name='publish_files')
    file_addr = models.FileField(u'附件', upload_to=get_file_path)
    file_name = models.CharField(u'名称', max_length=100)
    created_time = models.DateTimeField(u'上传时间', default=datetime.now())

######################----End Publish----##################

######################----Meeting--------##################

class Meeting(models.Model):
    # employee_id = models.CharField(u'用户ID', primary_key=True, max_length=100)
    user = models.ForeignKey(MyUser)
    name = models.CharField(u'名称', max_length=50)
    desc = models.TextField(u'描述', blank=True)
    file_addr = models.FileField(u'例会文件', upload_to=get_file_path)
    created_time = models.DateTimeField(u'上传时间', default=datetime.now)

    def __unicode__(self):
        # import pdb; pdb.set_trace()
        # x = 1 + 2
        return "Meeting--" + self.created_time.__str__()

    class Meta:
        ordering = ['-created_time']

class MeetingFile(models.Model):
    meeting = models.ForeignKey(Meeting, related_name='meeting_files')
    file_addr = models.FileField(u'附件', upload_to=get_file_path)
    file_name = models.CharField(u'名称', max_length=100)
    created_time = models.DateTimeField(u'上传时间', default=datetime.now())

######################----End Meeting----##################

######################----Training-------##################

class Training(models.Model):
    user = models.ForeignKey(MyUser)
    name = models.CharField(u'名称', max_length=50)
    desc = models.TextField(u'描述', blank=True)
    image = models.ImageField(u'图片', upload_to=get_file_path, max_length=255)
    video_url= models.URLField(u'视频地址', blank=True, max_length=300)
    created_time = models.DateTimeField(u'上传时间', default=datetime.now)

    def __unicode__(self):
        return "Training--" + self.created_time.__str__()

    class Meta:
        ordering = ['-created_time']

class TrainingFile(models.Model):
    training = models.ForeignKey(Training, related_name='training_files')
    file_addr = models.FileField(u'附件', upload_to=get_file_path)
    file_name = models.CharField(u'文件名称', max_length=100)
    created_time = models.DateTimeField(u'上传时间', default=datetime.now)

##############################################################

class TrainingV1(models.Model):

    user = models.ForeignKey(MyUser)
    name = models.CharField(u'培训名称', max_length=50)
    # image = models.ImageField(u'图片', upload_to=get_file_path, max_length=255)
    created_time = models.DateTimeField(u'上传时间', default=datetime.now)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u'培训'
        verbose_name_plural = u'培训'

class BoDuan(models.Model):
    training = models.ForeignKey(TrainingV1, related_name='training_bo_duan')
    bo_duan_name = models.CharField(u'波段名称', max_length=50)
    image = models.ImageField(u'图片', upload_to=get_file_path, max_length=255)
    created_time = models.DateTimeField(u'上传时间', default=datetime.now)

    def __unicode__(self):
        return self.bo_duan_name

    class Meta:
        verbose_name = u'波段'
        verbose_name_plural = u'波段'

class BoDuanFile(models.Model):
    bo_duan = models.ForeignKey(BoDuan, related_name='bo_duan_files')
    file_addr = models.FileField(u'附件', upload_to=get_file_path)
    file_name = models.CharField(u'文件名称', max_length=100)
    created_time = models.DateTimeField(u'上传时间', default=datetime.now)

    def __unicode__(self):
        return self.bo_duan.bo_duan_name

    class Meta:
        verbose_name = u'波段附件'
        verbose_name_plural = u'波段附件'

######################----End Training----##################

######################----Exhibiting------##################

class Exhibiting(models.Model):
    user = models.ForeignKey(MyUser)
    name = models.CharField(u'名称', max_length=50)
    file_addr = models.FileField(u'附件', upload_to=get_file_path)
    file_name = models.CharField(u'文件名称', max_length=100)
    shop_type = models.CharField(u'店铺类型', max_length=10)
    created_time = models.DateTimeField(u'上传时间', default=datetime.now)

    def __unicode__(self):
        return "Training--" + self.created_time.__str__()

    class Meta:
        ordering = ['-created_time']

class ExhibitingImage(models.Model):
    exhibiting = models.ForeignKey(Exhibiting, related_name='exhibiting_images')
    image = models.ImageField(u'图片', upload_to=get_file_path, max_length=255)
    created_time = models.DateTimeField(u'上传时间', default=datetime.now())

######################----End Exhibiting----##################

######################----notifacation------##################

class Notifacation(models.Model):
    user = models.ForeignKey(MyUser)
    name = models.CharField(u'标题', max_length=50)
    created_time = models.DateTimeField(u'上传时间', default=datetime.now)
    def __unicode__(self):
        return "Notifacation--" + self.created_time.__str__()

    class Meta:
        ordering = ['-created_time']

class NotifacationFile(models.Model):
    notifacation = models.ForeignKey(Notifacation, related_name='notifacation_files')
    file_addr = models.FileField(u'附件', upload_to=get_file_path)
    file_name = models.CharField(u'名称', max_length=100)
    created_time = models.DateTimeField(u'上传时间', default=datetime.now())

######################----End IpadHelp----##################

class IpadHelp(models.Model):
    user = models.ForeignKey(MyUser)
    file_addr = models.FileField(u'附件', upload_to=get_file_path)
    version = models.CharField(u'版本号', default='0', max_length=10, unique=True)
    created_time = models.DateTimeField(u'上传时间', default=datetime.now)
    
    def __unicode__(self):
        return "IpadHelp--" + self.created_time.__str__()

    class Meta:
        ordering = ['-created_time']

######################----End IpadHelp----##################

check/templates/ipad/exhibiting_add.html
{% extends "ipad/ipad_base.html" %}
{% load staticfiles %}

{% load formset_tags %}

{% load widget_tweaks %}

{% block extra_style %}
    <style type="text/css">
        ul li{
          list-style: none;
            display: inline-block;
            padding-left: 0;
            /*margin-left: -5px;*/
        }

        #id_shop_type{
            padding-left: 0;
          display: inline-block;
        }
    </style>
{% endblock %}

{% block extra_script %} 
  {{ trainingfile_formset.media }}
{% endblock %}

{% block content %}

    <div class="container">
        <script src="/static/jquery19/jquery-1.9.0.js"></script>
        <script type="text/javascript" src="/static/js/jquery.formset.js"></script>

        <div class="col-xs-12">
            <h3 class="text-center">修改陈列</h3>
        </div>

        <div class="row">
            <div class="col-xs-3"></div>
            <div class="col-xs-6">
                <form action="." method="post" enctype="multipart/form-data">{% csrf_token %}
            <div class="form-group">
              {{ exhibiting_form.name.errors }}
              {{ exhibiting_form.name.label_tag }}
              {{ exhibiting_form.name | add_class:"form-control" }}
            </div>

            <div class="form-group">
              {{ exhibiting_form.file_addr.errors }}
              {{ exhibiting_form.file_addr.label_tag }}
              {{ exhibiting_form.file_addr | add_class:"form-control" }}
            </div>

            <div class="form-group">
              {{ exhibiting_form.shop_type.errors }}
              {{ exhibiting_form.shop_type.label_tag }}
              {{ exhibiting_form.shop_type }}
            </div>

            {% load formset_tags %}

            <div id="formset" data-formset-prefix="{{ formset.prefix }}">
                {{ formset.management_form }}

                <div data-formset-body >
                    <!-- New forms will be inserted in here -->
                    {% for form in formset %}
                        <div data-formset-form>

                            <div class="form-group">
                              {{ form }}
                            </div>
                            <!-- <button type="button" data-formset-delete-button>Delete form</button> -->
                        </div>
                    {% endfor %}
                </div>

                <!-- The empty form template. By wrapping this in a <script> tag, the
                __prefix__ placeholder can easily be replaced in both attributes and
                any scripts -->
                <script type="form-template" data-formset-empty-form>
                    {% escapescript %}
                        <div data-formset-form>
                            {{ formset.empty_form }}
                           
                        </div>
                    {% endescapescript %}
                </script>

                <!-- This button will add a new form when clicked -->
                <hr>
                <input type="button" value="多添加一张图片" data-formset-add class="btn btn-default btn-sm">

                <script>jQuery(function($) {
                    $("#formset").formset();
                });</script>

            </div>

            <hr>

            <input type="submit" value="确定" class="btn btn-primary">

        </form>
        <div class="col-xs-3"></div>
            </div>
        </div>
        

    </div>



{% endblock %}

check/templates/ipad/exhibiting_list.html
{% extends "ipad/ipad_base.html" %}

{% load pagination_tags %}

{% load staticfiles %}


{% block extra_style %}
    <style type="text/css">
        .my_pic{
            max-height: 50px;
        }

        ul {
          list-style: none;
          margin-left: 0;
          padding-left: 0;
        }

        li {
          padding-left: 1em;
          text-indent: -1em;
        }

        li:before {
          content: " ";
          padding-right: 1px;
        }
    </style>
{% endblock %}

{% block extra_script %} 
<script type="text/javascript">
   
</script>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <table class="table">
                    <thead>
                        <tr>
                            <th class="col-xs-2">名字</th>
                            <th class="col-xs-1">店铺类型</th>
                            <th class="col-xs-2">文件</th>
                            <th class="col-xs-1">创建时间</th>
                            <th class="col-xs-2">图片</th>
                            <th class="col-xs-1">修改</th>
                            <th class="col-xs-1">删除</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for obj in object_list %}
                           <tr>
                                <td>{{ obj.exhibiting.name }}</td>
                                <td>{{ obj.exhibiting.shop_type }}</td>
                                <td><a href="{{ obj.exhibiting.file_addr.url }}">{{ obj.exhibiting.file_name }}</a></td>
                                <td>{{ obj.exhibiting.created_time }}</td>                                
                                <td>
                                    <ul style="display:">
                                        {% for im in obj.exhibiting_file %}
                                            <li>
                                                <a href="{{ im.image.url }}"><img class="img-responsive my_pic" src="{{ im.image.url }}"></a>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </td>
                                <td>
                                    <a class="btn btn-default" href="/ipad/admin/exhibiting/{{ obj.exhibiting.id }}/" role="button">修改</a>
                                </td>
                                <td>
                                    <a class="btn btn-default" href="/ipad/admin/exhibiting/{{ obj.exhibiting.id }}/delete" role="button">删除</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row">
          <div class="col-xs-12">
            <a class="btn btn-default" href="/ipad/admin/exhibiting/add/" role="button">添加</a>
          </div>
        </div>
    </div>
 
{% endblock %}

check/templates/ipad/ipad_base.html
{% extends "base.html" %}

{% load staticfiles %}
{% load metron_tags %}
{% load i18n %}

{% block site_brand %}<a class="navbar-brand" href="#">iPad</a>{% endblock %}

{% block extra_head_base %}
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    {% block extra_head %}{% endblock %}
{% endblock %}


{% block style_base %}
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "pinax/css/theme.css" %}" rel="stylesheet">
    <link href="{% static "css/justified-nav.css" %}" rel="stylesheet">
    <link href="{% static "css/site.css" %}" rel="stylesheet">
    <style type="text/css">
        /*.container {
            padding-right: 15px;
            padding-left: 15px;
            margin-right: auto;
            margin-left: auto;
            width: auto;
            }*/

    </style>
    {% block extra_style %}{% endblock %}
{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            
            <div class="col-xs-12">{% block content %}{% endblock %}</div>
        </div>
    </div>
{% endblock %}


{% block footer %}
    <div style="float:left;">
    <a href="http://jefen.com/" target="_blank"> {% trans "&copy; 2014 版权所有 北京吉芬时装设计股份有限公司 京ICP备05060825号-1" %}</a>
</div>

{% endblock %}


{% block extra_body_base %}
    {% analytics %}
    {% block extra_body %}{% endblock %}
{% endblock %}


{% block script_base %}
    <script src="{% block jquery_src %}{% static "jquery19/jquery-1.9.0.js" %}{% endblock %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "pinax/js/theme.js" %}"></script>
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="{% static "js/respond.min.js" %}"></script>
      <script src="{% static "js/html5shiv.min.js" %}"></script>
    <![endif]-->
    {% block extra_script %}{% endblock %}
{% endblock %}

check/templates/ipad/ipad_help_add.html
{% extends "ipad/ipad_base.html" %}

{% load widget_tweaks %}

{% load staticfiles %}

{% block extra_style %}{% endblock %}

{% block extra_script %}{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h3 class="text-center">添加帮助文件</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-3"></div>
            <div class="col-xs-6">
               
                <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}

                    <div class="form-group">
                      {{ form.file_addr.errors }}
                      {{ form.file_addr.label_tag }}
                      {{ form.file_addr | add_class:"form-control" }}
                    </div>
                    <div class="form-group">
                      {{ form.version.errors }}
                      {{ form.version.label_tag }}
                      {{ form.version | add_class:"form-control" }}
                    </div>
                    <input type="submit" value="确定" class="btn btn-primary">
                </form>
            </div>
           
        </div>
    </div>

{% endblock %}

check/templates/ipad/ipad_help_delete.html
{% extends "ipad/ipad_base.html" %}

{% load widget_tweaks %}

{% load staticfiles %}

{% block extra_style %}{% endblock %}

{% block extra_script %}{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h3 class="text-center">帮助文件</h3>
            </div>
        </div>

        <form action="" method="post">{% csrf_token %}
            <p>确定删除 "{{ object.file_addr }} 上传时间：{{ object.created_time }}"?</p>
            <input type="submit" value="确定" class="btn btn-primary">
        </form>
        
    </div>
{% endblock %}

check/templates/ipad/ipad_help_list.html
{% extends "ipad/ipad_base.html" %}


{% load staticfiles %}

{% block extra_style %}{% endblock %}

{% block extra_script %}{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h3 class="text-center">帮助文件</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <table class="table">
                    <tr>
                        <th>文件</th>
                        <th>版本</th>
                        <th>上传时间</th>
                        <th>修改</th>
                        <th>删除</th>
                    </tr>
                    {% for obj in object_list %}
                    <tr>
                        <td><a href="{{ obj.file_addr.url }}">{{ obj.file_addr.name }}</a></td>
                        <td>{{ obj.version }}</td>
                        <td>{{ obj.created_time }}</td>
                        <td>
                            <a class="btn btn-default" href="/ipad/admin/help/{{ obj.id }}/" role="button">修改</a>
                        </td>
                        <td>
                            <a class="btn btn-default" href="/ipad/admin/help/delete/{{ obj.id }}/" role="button">删除</a>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
                <div class="col-xs-12">
            <a class="btn btn-default" href="/ipad/admin/help/add/" role="button">添加</a>
          </div>
            </div>
        </div>
    </div>

{% endblock %}

check/templates/ipad/ipad_help_update.html
{% extends "ipad/ipad_base.html" %}

{% load widget_tweaks %}

{% load staticfiles %}

{% block extra_style %}{% endblock %}

{% block extra_script %}{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h3 class="text-center">帮助文件</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-3"></div>
            <div class="col-xs-6">
               
                <form action="" method="post">{% csrf_token %}

                    <div class="form-group">
                      {{ form.file_addr.errors }}
                      {{ form.file_addr.label_tag }}
                      {{ form.file_addr | add_class:"form-control" }}
                    </div>

                    <div class="form-group">
                      {{ form.version.errors }}
                      {{ form.version.label_tag }}
                      {{ form.version | add_class:"form-control" }}
                    </div>

                    <input type="submit" value="确定" class="btn btn-primary">
                </form>
                            
            </div>
            <div class="col-xs-3"></div>
        </div>
    </div>

{% endblock %}

check/templates/ipad/meeting_add.html
{% extends "ipad/ipad_base.html" %}
{% load staticfiles %}
{% block extra_style %}
{% load widget_tweaks %}
{% endblock %}

{% block extra_script %} 
<script type="text/javascript">
</script>
{% endblock %}

{% block content %}

    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <h3 class="text-center">添加例会</h3>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-3"></div>
          <div class="col-xs-6">
          <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
            <div class="form-group">
              {{ meeting_form.name.errors }}
              {{ meeting_form.name.label_tag }}
              {{ meeting_form.name | add_class:"form-control" }}
            </div>
            
            <div class="form-group">
              {{ meeting_form.desc.errors }}
              {{ meeting_form.desc.label_tag }}
              {{ meeting_form.desc |attr:"rows:3" |attr:"placeholder:可以不填" | add_class:"form-control" }} 
            </div>
            
            <div class="form-group">
              {{ meeting_form.file_addr.errors }}
              {{ meeting_form.file_addr.label_tag }}
              {{ meeting_form.file_addr | add_class:"form-control" }}
            </div>

            <div class="form-group">
              <input type="submit" value="确定" class="btn btn-primary" class="btn-block">
            </div>

            
          </form>
          </div>
          <div class="col-xs-3"></div>
      </div>
    </div>

{% endblock %}

check/templates/ipad/meeting_update.html
{% extends "ipad/ipad_base.html" %}
{% load staticfiles %}

{% load widget_tweaks %}
{% block extra_style %}
{% endblock %}

{% block extra_script %} 
<script type="text/javascript">
</script>
{% endblock %}

{% block content %}

    <div class="container">
        <div class="col-xs-12">
          <h3 class="text-center">修改例会</h3>
        </div>
        <div class="row">
          <div class="col-xs-3"></div>
            <div class="col-xs-6">
            <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
            <div class="form-group">
              {{ meeting_form.name.errors }}
              {{ meeting_form.name.label_tag }}
              {{ meeting_form.name | add_class:"form-control" }}
            </div>
            
            <div class="form-group">
              {{ meeting_form.desc.errors }}
              {{ meeting_form.desc.label_tag }}
              {{ meeting_form.desc |attr:"rows:3" | add_class:"form-control" |attr:"placeholder:可以不填" }} 
            </div>
            
            <div class="form-group">
              {{ meeting_form.file_addr.errors }}
              {{ meeting_form.file_addr.label_tag }}
              {{ meeting_form.file_addr | add_class:"form-control" }}
            </div>

            <input type="submit" value="确定" class="btn btn-primary">
          </form>
          <div class="col-xs-3"></div>
            </div>
        </div>
    </div>
{% endblock %}

check/templates/ipad/publish_add.html
{% extends "ipad/ipad_base.html" %}
{% load staticfiles %}

{% load widget_tweaks %}

{% block extra_style %}
{% endblock %}

{% block extra_script %} 
<script type="text/javascript">
</script>
{% endblock %}

{% block content %}

    <div class="container">
      <div class="col-xs-12">
          <h3 class="text-center">添加推广</h3>
        </div>

        <div class="row">
          <div class="col-xs-3"></div>
            <div class="col-xs-6">
            <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
            <div class="form-group">
              {{ publish_form.name.errors }}
              {{ publish_form.name.label_tag }}
              {{ publish_form.name | add_class:"form-control" }}
            </div>
            
            <div class="form-group">
              {{ publish_form.desc.errors }}
              {{ publish_form.desc.label_tag }}
              {{ publish_form.desc |attr:"rows:3" | add_class:"form-control" |attr:"placeholder:可以不填" }} 
            </div>
            
            <div class="form-group">
              {{ publish_form.file_addr.errors }}
              {{ publish_form.file_addr.label_tag }}
              {{ publish_form.file_addr | add_class:"form-control" }}
            </div>

            <input type="submit" value="确定" class="btn btn-primary">
          </form>
          <div class="col-xs-3"></div>
            </div>
        </div>
    </div>

{% endblock %}