check/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView, RedirectView
from django.contrib import admin



urlpatterns = patterns(

    "",
    # url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),
    # url(r"^$", "checkapp.views.homepage", name="home"),
    
    url(r'^$', RedirectView.as_view(url='/account/login/'), name="home"),
    url(r"^check/", include("checkapp.urls")),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^account/", include("account.urls")),
    url(r"^ipad/", include("ipad.urls")),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# print urlpatterns

checkapp/urls.py
from django.conf import settings
from django.conf.urls import patterns, url
import views_account
from FeedbackListView import FeedbackListView
from RotaUpdateView import RotaUpdateView
import ManagerView



urlpatterns = patterns(
    "checkapp.views",
    url(r'^gotopage/$', 'gotopage', name='gotopage'),
    url(r'^rotas/$', 'rotas', name='rotas'),
    url(r'^rotassetup/$', 'rotassetup', name='rotassetup'),
    url(r'^rotasdelete/$', 'rotasdelete', name='rotasdelete'),
    url(r'^rotascomfirm/$', 'rotascomfirm', name='rotascomfirm'),
    url(r'^employeeinfo/$', 'employeeinfo', name='employeeinfo'),
    url(r'^report/$', 'report', name='report'),
    url(r'^report_print/$', 'report_print', name='report_print'),
    url(r'^report_note/$', 'report_note', name='report_note'),
    
    url(r'^help/$', 'help', name='help'),
    url(r'^feedback/$', 'feedback', name='feedback'),
    url(r'^list_feedback/$', FeedbackListView.as_view(), name='list_feedback'),
    url(r'^list_feedback/delete/$', 'delete_feedback', name='delete_feedback'),

    url(r'^schedule_work_time/$', 'schedule_work_time', name='schedule_work_time'),
    url(r'^regionalmanager_report/$', 'regionalmanager_report', name='regionalmanager_report'),
    url(r'^regionalmanager/$', 'regionalmanager', name='regionalmanager'),
 
    url(r'^test/$', 'test', name='test'),
    # aiax
    url(r'^rotas/setuprota/$', 'setuprota', name='setuprota'),
    url(r'^loadPic/$', 'loadPic', name='loadPic'),
    url(r'^confirm_modify_button/$', 'confirm_modify_button', name='confirm_modify_button'),

    # rotas
    url(r'^rotas/update/(?P<pk>\d+)/$', RotaUpdateView.as_view(), name='rota_update'),

    # API
    url(r'^loginValidation/$', 'loginValidation', name='loginValidation'),
    url(r'^uploadImageInfoCheckin/$', 'uploadImageInfoCheckin', name='uploadImageInfoCheckin'),
    url(r'^uploadImageInfoCheckout/$', 'uploadImageInfoCheckout', name='uploadImageInfoCheckout'),
    url(r'^getEmployeesInfo/$', 'getEmployeesInfo', name='getEmployeesInfo'),
    
    # lixin
    url(r'^SetManager/$', views_account.Default, name='Default'),
    url(r'^SetManager/GetShopJs/$', views_account.GetShopJs, name='GetShopJs'),
    url(r'^SetManager/GetEmployeesJs/$', views_account.GetEmployeesJs, name='GetEmployeesJs'),
    url(r'^SetManager/SaveDz/$', views_account.SaveDz, name='SaveDz'),
    url(r'^SetManager/SaveScheduledRotas/$', views_account.SaveScheduledRotas, name='SaveScheduledRotas'),

    # get user's check in and check out
    url(r'^sl38doselkklglyhhkoj7580/$', ManagerView.GetSingleUserCheck.as_view(), name='get_single_user_check'),

)

ipad/urls.py
from django.conf import settings
from django.conf.urls import patterns, url, include
from rest_framework.authtoken import views as token_view
# import views_account
from rest_framework import routers
from ipad import views
from ipad import admin_view


router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'publish', views.PublishViewSet)
router.register(r'publish_v1', views.PublishViewSetV1, base_name="publish_v1")
router.register(r'meeting', views.MeetingViewSet)
router.register(r'meeting_v1', views.MeetingViewSetV1, base_name="meeting_v1")
router.register(r'exhibiting', views.ExhibitingViewSet)
router.register(r'training', views.TrainingViewSet)
router.register(r'training_v1', views.TrainingViewSetV1)
router.register(r'notifacation', views.NotifacationViewSet)
router.register(r'notifacation_v1', views.NotifacationViewSetV1, base_name="notifacation_v1")
router.register(r'help', views.IpadHelpViewSet)
router.register(r'updatetime', views.UpdateTimeViewSet, base_name="updatetime")
router.register(r'meeting_date', views.MeetingAvaiableDate, base_name="meeting_date")
router.register(r'notification_date', views.NotificationAvaiableDate, base_name="notification_date")
router.register(r'publish_date', views.PublishAvaiableDate, base_name="publish_date")

urlpatterns = patterns(
    "ipad.views",
    url(r'^api-token-auth/', token_view.obtain_auth_token),
    url(r'^api/', include(router.urls)),
    # url(r'^api/updatetime/$', views.update_time, name='updatetime'),
    # url(r'^api/getupdatetime/$', views.GetUpdateTime.as_view(), name='getupdatetime'),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # 
    url(r'^api/terms_of_service/$', views.terms_of_service, name='terms_of_service'),

    # admin
    # publish
    url(r'^admin/publish/$', admin_view.publish_list, name="publish_list"),
    url(r'^admin/publish/(?P<pk>\d+)/$', admin_view.publish_update),
    url(r'^admin/publish/(?P<pk>\d+)/delete/$', admin_view.publish_delete),
    url(r'^admin/publish/add/$', admin_view.publish_add),

    # meeting
    url(r'^admin/meeting/$', admin_view.meeting_list, name="meeting_list"),
    url(r'^admin/meeting/(?P<pk>\d+)/$', admin_view.meeting_update),
    url(r'^admin/meeting/(?P<pk>\d+)/delete/$', admin_view.meeting_delete),
    url(r'^admin/meeting/add/$', admin_view.meeting_add),

    # training
    url(r'^admin/training/$', admin_view.training_list, name="training_list"),
    url(r'^admin/training/(?P<pk>\d+)/$', admin_view.training_update),
    url(r'^admin/training/(?P<pk>\d+)/delete/$', admin_view.training_delete),
    url(r'^admin/training/add/$', admin_view.training_add),

    # exhibition
    url(r'^admin/exhibiting/$', admin_view.exhibiting_list, name="exhibiting_list"),
    url(r'^admin/exhibiting/(?P<pk>\d+)/$', admin_view.exhibiting_update),
    url(r'^admin/exhibiting/(?P<pk>\d+)/delete/$', admin_view.exhibiting_delete),
    url(r'^admin/exhibiting/add/$', admin_view.exhibiting_add),

    # noticafacion
    url(r'^admin/notification/$', admin_view.notifacation_list, name='notifacation_list'),
    url(r'^admin/notification/(?P<pk>\d+)/$', admin_view.notifacation_update),
    url(r'^admin/notification/add/$', admin_view.notifacation_add, name='notifacation_add'),
    url(r'^admin/notification/(?P<pk>\d+)/delete/$',  admin_view.notifacation_delete, name='notifacation_delete'),

    # help
    # 
    url(r'^admin/help/$', admin_view.IpadHelpList.as_view(template_name="ipad/ipad_help_list.html"), name='help_list'),
    url(r'admin/help/(?P<pk>\d+)/$', admin_view.IpadHelpUpdate.as_view(template_name="ipad/ipad_help_update.html"), name='help_update'),
    url(r'admin/help/delete/(?P<pk>\d+)/$', admin_view.IpadHelpDelete.as_view(template_name="ipad/ipad_help_delete.html"), name='help_delete'),
    url(r'admin/help/add/$', admin_view.IpadHelpAdd.as_view(template_name="ipad/ipad_help_add.html"), name='help_add'),

    # file to client
    # url(r'^file_to_client/$', views.file_to_client, name='file_to_client'),

    # backend admin
    # url(r'^publish/$', 'publish', name='publish'),
)

checkapp/models.py
# -*- coding: utf-8 -*- 

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from datetime import datetime



class Employees(models.Model):
    employee_id = models.CharField(u'用户ID', primary_key=True, max_length=100)
    name = models.CharField(u'姓名', max_length=50)
    shop_id = models.CharField(u'店铺ID', max_length=50)
    # 0: 在职 1: 离职
    status = models.BooleanField(u'在职状态', default=True)
    is_updated = models.IntegerField(u'已更新', default=0)

    def __unicode__(self):
        return self.name

class EmployeesForm(ModelForm):

    class Meta:
        model = Employees
        fields = ('employee_id', 'name', )

# Create your models here.
class MyUser(AbstractUser):
    user_type = models.IntegerField(u'用户类型', default=0)
    shop_name = models.CharField(u'店铺名称', max_length=50)
    shop_id = models.CharField(u'店铺ID', max_length=50)
    shop_status = models.IntegerField(u'店铺状态', default=1)
    edit_rotas = models.BooleanField(u'班次编辑', default=1)
    manager = models.ForeignKey(Employees)
    scheduledRotas = models.IntegerField(u'店长在本店排班', default=0)

    is_opened = models.IntegerField(u'已更新', default=1)


    def __unicode__(self):
        return self.username + '-' + self.shop_name

class FeedBack(models.Model):
    user = models.ForeignKey(MyUser)
    desc = models.CharField(u'描述', max_length=400)
    created_time = models.DateTimeField(u'创建时间', default=datetime.now())

class FeedBackForm(ModelForm):
    # import pdb; pdb.set_trace()
    desc = forms.CharField(label=u'', widget=forms.Textarea(attrs={'cols': 80, 'rows': 5, 'placeholder': u'在这里输入'}))
    class Meta:
        model = FeedBack
        fields = ('desc',)


class Rotas(models.Model):
    user = models.ForeignKey(MyUser)
    name = models.CharField(u'班次名称', max_length=50)
    rota_type = models.CharField(u'班次类型(上班1,非上班0)', max_length=1, default=1)
    is_common = models.IntegerField(u'公共', default=0)
    report_color_id = models.CharField(u'报表颜色ID', default="0000", max_length=50)
    start_time = models.TimeField(u'开始时间', default="08:00")
    end_time = models.TimeField(u'结束时间', default="08:00")
    color = models.CharField(u'显示颜色', max_length=20)
    created_time = models.DateTimeField(u'创建时间', default=datetime.now())

    def __unicode__(self):
        return str(self.id)  + " . " +  self.name + "--" + self.user.username + '--' + self.user.shop_name

# class ReportColor(models.Model):
#     '''
#         1001：迟到：  insert into checkapp_reportcolor values(1, '迟', '#d06b64', 1001)
#         1002：正常：  insert into checkapp_reportcolor values(2, '到', '#fa573c', 1002)
#         1003：早退：  insert into checkapp_reportcolor values(3, '早', '#fa573c', 1003)
#         1004：未签到：insert into checkapp_reportcolor values(4, '未签到', '#fa573c', 1004)
#         1005：未签出：insert into checkapp_reportcolor values(5, '未签出', '#fa573c', 1005)
#         1006：缺勤：  insert into checkapp_reportcolor values(6, '缺', '#fa573c', 1006)
#         1007：未排班：insert into checkapp_reportcolor values(7, '未排班', '#fa573c', 1007)
#     '''
#     report_type = models.CharField(u'出勤类型ID',  max_length=20)
#     name = models.CharField(u'名称', max_length=20)
#     color = models.CharField(u'显示颜色', max_length=20)

class ScheduledRotas(models.Model):
    employee = models.ForeignKey(Employees)
    rota = models.ForeignKey(Rotas)
    # 0-6
    weekdayNum = models.IntegerField()
    scheduled_day = models.DateField()

    def __unicode__(self):
        return self.employee.name + "-" + self.scheduled_day.__str__()

def getFilePath(instance, filename):

    # import pdb; pdb.set_trace()
    date = instance.check_time
    date = date.replace(":", "-")

    filename = instance.__class__.__name__ + "/" + instance.employee.shop_id + "/" + instance.check_day + "/" + instance.employee_id + "_" + date + ".jpg"
    return filename


class Checkin(models.Model):
    employee = models.ForeignKey(Employees)
    check_day = models.DateField()
    check_time = models.TimeField()
    image_path = models.ImageField(upload_to=getFilePath, max_length=255)
    shop_id = models.CharField(u'店铺ID', max_length=50)

    def __unicode__(self):
        return self.employee.name + "-" + self.check_day.__str__() + " " + self.check_time.__str__()


class Checkout(models.Model):
    employee = models.ForeignKey(Employees)
    check_day = models.DateField()
    check_time = models.TimeField()
    image_path = models.ImageField(upload_to=getFilePath, max_length=255)
    shop_id = models.CharField(u'店铺ID', max_length=50)

    def __unicode__(self):
        return self.employee.name + "-" + self.check_day.__str__() + " " + self.check_time.__str__()


class ImageForm(ModelForm):
    class Meta:
        model = Checkin
        fields = ('image_path', )

class MonthReportNote(models.Model):
    # 201501 = Yesr + month
    report_id = models.CharField(u'报表ID', max_length=20)
    note = models.CharField(u'添加备注', null=False, max_length=1000)
    created_time = models.DateTimeField(u'创建时间', default=datetime.now())
    user = models.ForeignKey(MyUser)
    # 1 commit 0 can edit
    commited = models.IntegerField(u'确认', default=0)

    def __unicode__(self):
        return self.user.username +"-"+ self.report_id

class MonthReportNoteForm(ModelForm):
    # import pdb; pdb.set_trace()
    # note = forms.CharField(label=u'备注', widget=forms.Textarea(attrs={'cols': 80, 'rows': 3, 'placeholder': u'备注'}))
    class Meta:
        model = MonthReportNote
        # fields = ('name', 'rota_type', 'start_time', 'end_time', 'color')
        fields = ('note',)


 
# END_TIME_CHOICE = ( 
#     ('', u"选择时间"), 
#     (2, u"2"),         
#     (4, u"4"),         
#     (8, u"8"), 
#     (16, u"16"), 
# ) 

rota_type_choice = (
    (1, u'上班'),
    (0, u'非上班'),
)

COLOR_CHOICE = (
    ("#16a765", "#16a765"),
    ("#fad165", "#fad165"),
    ("#ac725e", "#ac725e"),
    ("#d06b64", "#d06b64"),
    ("#f83a22", "#f83a22"),
    ("#fa573c", "#fa573c"),
    ("#ff7537", "#ff7537"),
    ("#ffad46", "#ffad46"),
    ("#42d692", "#42d692"),
    ("#7bd148", "#7bd148"),
    ("#b3dc6c", "#b3dc6c"),
    ("#fbe983", "#fbe983"),
    ("#92e1c0", "#92e1c0"),
    ("#9fe1e7", "#9fe1e7"),
    ("#9fc6e7", "#9fc6e7"),
    ("#4986e7", "#4986e7"),
    ("#9a9cff", "#9a9cff"),
    ("#b99aff", "#b99aff"),
    ("#c2c2c2", "#c2c2c2"),
    ("#cabdbf", "#cabdbf"),
    ("#cca6ac", "#cca6ac"),
    ("#f691b2", "#f691b2"),
    ("#cd74e6", "#cd74e6"),
    ("#a47ae2", "#a47ae2"),
)

class RotasForm(ModelForm):
    rota_type = forms.ChoiceField(
        label=u"班次类型",
        required=True,
        choices=rota_type_choice,
        widget=forms.RadioSelect(),
        initial='1',
    )
    color = forms.ChoiceField(label=u"显示颜色", required=True, choices=COLOR_CHOICE)
    class Meta:
        model = Rotas
        # fields = ('name', 'rota_type', 'start_time', 'end_time', 'color')
        fields = ('id','name', 'rota_type', 'start_time', 'end_time', 'color')

check/templates/checkapp/employeeinfo.html
{% extends "site_base.html" %}

{% load staticfiles %}

{% block my_top_nav %}
    <li><a id="" href="/check/help" target="_blank">使用说明</a></li>
{% endblock %}

{% block extra_style %}
    <link href="{% static "css/jquery-ui.min.css" %}" rel="stylesheet">
{% endblock %}

{% block extra_script %}
    <script src="{% static "js/jquery-ui.min.js" %}"></script>
{% endblock %}

{% block content %}

  <div class="row">
    <div class="col-xs-12">
      <table class="table">
    <tr>
      <th>员工ID</th>
      <th>姓名</th>
      <th>店铺编号</th>
    </tr>
    {% for e in employees %}

    <tr>
      <td>{{ e.employee_id }}</td>
      <td>{{ e.name }}</td>
      <td>{{ e.shop_id }}</td>
    </tr>
    {% endfor %}
    </table>
    </div>
    

  </div>
    



{% endblock %}

check/templates/checkapp/feedback.html
{% extends "site_base.html" %}

{% load staticfiles %}

{% block extra_style %}
{% endblock %}

{% block extra_script %}

{% endblock %}

{% block my_top_nav %}
    <li><a id="" href="/check/help" target="_blank">使用说明</a></li>
{% endblock %}

{% block body %}

<div class="container">
  
  <div class="row">
    <div class="col-xs-12">
        <p>您的意见对我们非常重要，我们会认真对待每一条反馈:</p>
        <form action="/check/feedback/" method="POST">{% csrf_token %}
            <!-- <table class="table"> -->
                {{ form.as_p }}
            <!-- </table> -->
            <input type="submit" class="btn btn-info" value="发出去">
        <form>
        {% if message %}
            {{ message }}
        {% endif %}
    </div>
  </div>


</div>
{% endblock %}

check/templates/checkapp/get_single_user_check.html
{% extends "site_base.html" %}

{% load staticfiles %}


{% block content %}
    <form action='.' method='post'>{% csrf_token %}
        {{ form }}
        <input class="btn btn-primary" type='submit' id="submit_note" value='查询'>
    </form>

    {% for obj in object_list %}
        <hr>
        <table class="table table-striped">
        <tr>
            <th>员工id</th>
            <th>日期</th>
            <th>上班打卡</th>
            <th>下班打卡</th>
        </tr>
        {% for sub_obj in obj %}
            <tr>
                <td>{{ sub_obj.employee_id }}</td>
                <td>{{ sub_obj.check_day }}</td>
                <td>{{ sub_obj.checkin_time }}</td>
                <td>{{ sub_obj.checkout_time }}</td>
            </tr>
            
        {% endfor %}
        </table>
    {% endfor %}
{% endblock %}

check/templates/checkapp/help.html
{% extends "site_base.html" %}

{% load staticfiles %}

{% block extra_style %}
<style>
  .D24{font-size:24px; color:#FF0000; text-align: center;}
  .D18{font-size:18px; color:#000000; text-align: left;}
  .D12{font-size:12px; color:#000000; text-align: left; padding:20px; }
  .ZD{font-size:14px; color:#FF0000; text-align: left; padding:40px; }
  img{border: 1px solid #cccccc;}
</style>
{% endblock %}

{% block extra_script %}

{% endblock %}

{% block my_top_nav %}
    <li><a id="" href="/check/help" target="_blank">使用说明</a></li>
{% endblock %}

{% block body %}

<div class="container">
  
  <div class="row">
    <div class="D24">排班、考勤报表使用说明</div>
    <div class="D18">一、人员排班设置</div>
    <div class="D12">1.1 打开浏览器输入 <a href='http://tg.jefen.com:90'  target='blank'>http://tg.jefen.com:90</a> ,访问排班系统.</div>
    <img src="{% static "helpimg/http_login.jpg" %}">
    <div class="D12">1.2 登陆成功界面.</div>
    <img src="{% static "helpimg/http_login_ok.jpg" %}">
    <div class="D12">1.3 点击 员工信息 可以查看本店的人员信息,对于离职人员和新入职的员工，请参照POS系统的营业员维护方法.
      [<span style="color:#ff0000">注意:在POS系统维护人员后，排班系统信息需要24小时生效。</span>]</div>
    <img src="{% static "helpimg/http_dianyuan_info.jpg" %}">
    <div class="D12">1.4 点击 班次设置 可以根据本店的班次情况设置班次。</div>
    <img src="{% static "helpimg/http_bc_add.jpg" %}">
    <div class="D12">1.5 修改班次。</div>
    <img src="{% static "helpimg/http_bc_edit.jpg" %}">
    <div class="D12">1.6 点击 排版管理 设置每个员工的排班情况</div>
    <img src="{% static "helpimg/http_bc_setup.jpg" %}">
    <div class="D12">1.7 点击 统计报表 查看本店考勤情况</div>
    <img src="{% static "helpimg/http_view.jpg" %}">
    <div class="D12">1.8 统计报表 其它信息.</div>
    <img src="{% static "helpimg/http_note.jpg" %}"><br><br>
    <img src="{% static "helpimg/http_hz.jpg" %}"><br><br>
    <img src="{% static "helpimg/http_tl.jpg" %}">
  </div>

  <br><br><br>

  <div class="row">
    <div class="D24">客户端使用说明</div>
    <div class="D18">二、考勤系统客户端登陆</div> 
    <div class="D12">2.1 双击桌面上的考勤图标,打开考勤程序.</div> 
    <img src="{% static "helpimg/client_ico.jpg" %}">
    <div class="D12">2.2 输入POS系统的操作员账号密码登陆.</div>
    <img src="{% static "helpimg/login_client.jpg" %}">
    <div class="D12">2.3 登陆成功后的界面.</div>
    <img src="{% static "helpimg/client_login_ok.jpg" %}">
    <div class="D12">2.4 员工考勤操作流程。<br>
      <div class="ZD">
      2.4.1 选择右侧的员工姓名.<br>
      2.4.2 在点击左侧的启动摄像头<br>
      2.4.3 摄像头显示考勤人员的图像后，根据情况点击上班或下班按钮即可完成考勤.<br>
      2.4.5 考勤完成后，只要电脑能访问外网，即可登录考勤报表实时查看考勤结果.
      </div>
    </div>


  </div>

</div>
{% endblock %}

check/templates/checkapp/regional_manager.html
{% extends "site_base.html" %}

{% load staticfiles %}

{% block extra_style %}
  
{% endblock %}

{% block extra_script %}
   
    
{% endblock %}

{% block my_top_nav %}
    <li><a id="" href="/check/help" target="_blank">使用说明</a></li>
{% endblock %}

{% block content %}

  <table class="table">
      <tr>
          <th>用户ID</th>
          <th>姓名</th>
          <th>在职</th>
      </tr>
      {% for item in regional_manager %}
      <tr> 
          <td>{{ item.employee_id }}</td>
          <td>{{ item.name }}</td>
          {% if item.status == 0 %}
              <td>在职</td>
          {% else %}
              <td>离职</td>
          {% endif %}
      </tr>
      {% endfor %}
  </table>

  <form action="/check/regionalmanager/" method="post">{% csrf_token %}
    {{ employees_form.as_table }}
    <input class="btn btn-primary" type='submit' id="submit_note" value='保存'>
  </form>

{% endblock %}

check/templates/checkapp/rotascomfirm.html
{% extends "site_base.html" %}

{% load staticfiles %}

{% block extra_style %}
    <link href="{% static "MiniColors/jquery.minicolors.css" %}" rel="stylesheet">
    <link href="{% static "jquerytimepicker/jquery.timepicker.css" %}" rel="stylesheet">
    <link href="{% static "colorpicker/jquery.simplecolorpicker.css" %}" rel="stylesheet">
    <link href="{% static "colorpicker/jquery.simplecolorpicker-fontawesome.css" %}" rel="stylesheet">
    <style type="text/css">
       
    </style>
{% endblock %}

{% block my_top_nav %}
    <li><a id="" href="/check/help" target="_blank">使用说明</a></li>
{% endblock %}

{% block extra_script %}
    
    <script type="text/javascript">
        function comfirm(){
            var user_id = $("#comfirm_button").attr("user_id")
            // var edit_rotas = $("#comfirm_button").attr("edit_rotas")
            $.ajax({
                type:'POST',
                url:'/check/confirm_modify_button/',
                data:{"user_id": user_id, "edit_rotas": false},
                cache:false,
                success:function(data){
                    $("#comfirm_button").attr('disabled',true); 
                    $("#modify_button").attr('disabled',false);
                    return;
                }
            });
            // console.log("cell_id");
            
        };

        function modify(){
            var user_id = $("#comfirm_button").attr("user_id")
            // var edit_rotas = $("#comfirm_button").attr("edit_rotas")
            $.ajax({
                type:'POST',
                url:'/check/confirm_modify_button/',
                data:{"user_id": user_id, "edit_rotas": true},
                cache:false,
                success:function(data){
                    $("#comfirm_button").attr('disabled',false); 
                    $("#modify_button").attr('disabled',true);
                    return;
                }
            });
            
        };

    </script>
   
{% endblock %}

{% block content %}

        <div class="row">
            <form action='/check/rotascomfirm/' method='post'>{% csrf_token %}
            <div class="col-xs-3">
                <select name="user_id" class="form-control">
                    {% for x in data.data %}
                        <option value={{ x.user_id }} 
                        {% if x.user_id == data.default.user_id %} 
                            selected
                        {% endif %}
                        >{{ x.shop_name }}</option>
                    {% endfor %}
                </select>
            
            </div>
            <div class="col-xs-9"><input type='submit' class="btn btn-primary" value='提  交'></div>
            </form>

        </div>
        <hr>
        <div class="row">
            <div class="col-xs-6">
                <table class="table">
                    <tr>
                        <th>班次名称</th>
                        <th>班次类型</th>
                        <th>起止时间</th>
                        <th>显示颜色</th>
                    </tr>
                    {% for r in rotas_list %}
                    <tr>
                        <td>{{ r.name }}</td>
                        <td>{% if r.rota_type == "1" %}上班{% else %}非上班{% endif %}</td>
                        <td>{% if r.rota_type == "1" %}{{ r.start_time }}~{{ r.end_time }}{% else %} --------------- {% endif %}</td>
                        <td style="background-color: {{ r.color }}">{{ r.color }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>        
        
        <div class="row">
            <div class="col-xs-6">
                <table class="table">
                <tr>
                    {% if data.default.edit_rotas %}
                        <td><button id="comfirm_button" type="button" onclick="comfirm()" class="btn btn-primary" edit_rotas={{ data.default.edit_rotas }} user_id={{ data.default.user_id }}>确认</button></td>
                        <td><button id="modify_button" type="button"  onclick="modify()" class="btn btn-primary" disabled="true" edit_rotas={{ data.default.edit_rotas }} user_id={{ data.default.user_id }}>允许修改</button></td>
                    {% else %}
                        <td><button id="comfirm_button" type="button" onclick="comfirm()" class="btn btn-primary" disabled="true" edit_rotas={{ data.default.edit_rotas }} user_id={{ data.default.user_id }}>确认</button></td>
                        <td><button id="modify_button" type="button"  onclick="modify()"  class="btn btn-primary" edit_rotas={{ data.default.edit_rotas }} user_id={{ data.default.user_id }}>允许修改</button></td>
                    {% endif %}
                </tr>
            </table>
            </div>
            <div class="col-xs-6">

            </div>
        </div>
        
{% endblock %}